### PR TITLE
fix(retry): export RETRYABLE_ERR_FN_DEFAULT

### LINKED ISSUE #2516: Cannot import  RETRYABLE_ERR_FN_DEFAULT
**Is your feature request related to a problem? Please describe.**
I want to import RETRYABLE_ERR_FN_DEFAULT to be able to customize it
 **Describe the solution you'd like**
export RETRYABLE_ERR_FN_DEFAULT
 **Describe alternatives you've considered**
Copying the code into my repo is my current option, but this will drift from upstream over time, and hurts Google's ability to provide good service through GCS to nodejs consumers, imo.
 **Additional context**

### PR DESCRIPTION
**Pull request by Cynocracy**
Fixes https://github.com/googleapis/nodejs-storage/issues/2516

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
Thank you for the contribution @Cynocracy. One small request, can you amend the commit to be `fix` instead of `retry`. This likely should have been exported previously.

**Comment by ddelgrosso1** [comment]
Apologies, see my comments on the issue.

**Comment by Cynocracy** [comment]
roger, will continue discussion in the issue

**Comment by ddelgrosso1** [comment]
Ok I'm good with exporting this. If you can just update the commit message I can get this merged / released.

**Comment by Cynocracy** [comment]
@ddelgrosso1 thanks! Updating it now

**Comment by ddelgrosso1** [comment]
Failures are not related to anything you did. This is being fixed in another PR.

**Review by ddelgrosso1 — APPROVED** [review]

**Comment by ddelgrosso1** [comment]
@Cynocracy if you merge main into your branch this should now pass the CI tests and we can merge.

**Comment by Cynocracy** [comment]
updated!

**Comment by ddelgrosso1** [comment]
Thanks for the contribution @Cynocracy. I'll release this with `7.13.0` first thing tomorrow.

**Pull request merged**
