### PR TITLE
feat: add request timeout configuration to storage object and its methods

### PR DESCRIPTION
**Pull request by AVaksman**
Towards #733

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

This would be a first step to expose `request.timeout` configuration to storage functions.

### CODE REVIEW

**Comment by AVaksman** [comment]
Will it make seance to enable `timeout` on the `[service](https://github.com/googleapis/nodejs-common/blob/master/src/service.ts#L103)` and make it available to other client APIs?

**Comment by jkwlui** [comment]
I feel like we should expose it at the @google-cloud/common level, as @AVaksman suggested. @stephenplusplus thought?

**Comment by stephenplusplus** [comment]
Yes, the lower level, the better!

**Comment by AVaksman** [comment]
Thank you, closing this PR and preparing changes for @google-cloud/common level.

**Pull request closed without merging**
