### PR TITLE
docs: rename setTemporarydHold and address README

### PR DESCRIPTION
**Pull request by tchupp**
file `samples/setTemporarydHold.js` also needs to be renamed, but I'm not sure if there are other reference to this that might break

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [N/A] Ensure the tests and linter pass
- [N/A] Code coverage does not decrease (if any source code was changed)
- [N/A] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by laljikanjareeya — CHANGES_REQUESTED** [review]
@tchupp Thanks for the PR Please rename the file `samples/setTemporarydHold.js` and see below reference for same:
https://github.com/googleapis/nodejs-storage/blob/b80c025f106052fd25554c64314b3b3520e829b5/samples/setTemporarydHold.js#L37
https://github.com/googleapis/nodejs-storage/blob/b80c025f106052fd25554c64314b3b3520e829b5/samples/setTemporarydHold.js#L44
https://github.com/googleapis/nodejs-storage/blob/84ee6cc10226ea32596ab938fbfda7639aea79f7/samples/system-test/bucketLock.test.js#L118
[Samples README](https://github.com/googleapis/nodejs-storage/blob/master/samples/README.md)

**Review by bcoe — APPROVED** [review]

**Comment by laljikanjareeya** [comment]
@googlebot I fixed it.

**Comment by laljikanjareeya** [comment]
@googlebot I consent.

**Comment by laljikanjareeya** [comment]
@bcoe docs tests are failing because of rename the file name sample.

**Review by JustinBeckwith — APPROVED** [review]

**Pull request merged**
