### PR TITLE
docs(cloud-rad): move comments for TSDoc

### PR DESCRIPTION
**Pull request by fhinkel**
TSDoc expects comments before the first overloaded function.

See b/190631834

### CODE REVIEW

**Comment by shaffeeullah** [comment]
@fhinkel do you have a script that will remove all the documentation from the last definition (after we've fully migrated)? or will that be manual work for us? 

@ddelgrosso1 fyi: this duplicates all the documentation due to differences in TSDoc (cloud rad) and JSDoc (googleapis.dev documentation). For cloud-rad, the comments for overloaded functions are moved from the last definition to the first. See https://b.corp.google.com/issues/190631834

**Comment by fhinkel** [comment]
Mostly manual work. Feel free to assign that to me.

**Comment by shaffeeullah** [comment]
Synced with @fhinkel offline. We will wait to merge this as a last step and remove the documentation before the last function in this same PR.

**Review by bcoe — APPROVED** [review]

**Comment by fhinkel** [comment]
This is ready for review. Please have a look at the docs generated from this PR: https://cloud.google.com/nodejs/docs/reference/storage/latest

**Comment by fhinkel** [comment]
DO NOT MERGE without reverting the changes for systems-tests back to normal.

**Comment by shaffeeullah** [comment]
@tbpg closing this for now. please re-open when resuming work on this project.

**Pull request closed without merging**
