### PR TITLE
fix(deps): update fast-xml-parser to 4.4.1 due to security vulnerability

### LINKED ISSUE #2504: Security vulnerability with fast-xml-parser dependency
#### Environment details
  - `@google-cloud/storage` version: 7.12.0

`@google-cloud/storage` has a dependency on the `fast-xml-parser` package, and a [ReDoS vulnerability](https://github.com/advisories/GHSA-mpg4-rc92-vx8v) was reported on that package a few days ago. I see you're using v4.3.2 which contains the vulnerability, but there was a safe version (4.4.1) released to fix the vulnerability. Could you upgrade the package to `>= 4.4.1` use a safe version of `fast-xml-parser`?

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2504  🦕

### CODE REVIEW

**Comment by husf-dsheremata** [comment]
Bump!  Eagerly awaiting for this to get merged, so we can squash our security review findings!

Tx!

**Comment by ddelgrosso1** [comment]
@husf-dsheremata since we don't provide a `package-lock.json` with our releases it should be possible to update on the application side, no?

**Review by danielduhh — APPROVED** [review]

**Review by danielbankhead — APPROVED** [review]

**Comment by husf-dsheremata** [comment]
> @husf-dsheremata since we don't provide a `package-lock.json` with our releases it should be possible to update on the application side, no?

Good point - thanks!

Even still, it's cleaner and easier to just wait for your fix.   

Much appreciated!

**Comment by ddelgrosso1** [comment]
@husf-dsheremata this was released with version `7.12.1`. Thanks for bringing it to our attention!

**Pull request merged**
