### PR TITLE
test: add tests for OLM MPU

### LINKED ISSUE #1834: Add support for AbortIncompleteMultipartUpload LifecycleAction
This feature adds the following capabilities to the existing GCS Lifecycle APIs:
- A new type of LifecycleAction -  `AbortIncompleteMultipartUpload` will be added. 

**If there are code changes other than documentation to implement this feature, please add the following system tests:**

- Validate that “AbortIncompleteMultipartUpload” lifecycle action can be set via Bucket Create, Patch and Update operations.
- Bucket Get and List operations should return the correct state of the lifecycle configuration on the bucket which includes the rules with the new action if present.

**If no code changes are required, verify that there are tests proving strings are properly propagated.**

Internal: see [go/gcs-dpe-olm-mpu](http://go/gcs-dpe-olm-mpu) for more info.

Please wait for approval from myself before merging or releasing this change so we can coordinate around release dates.

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1834  🦕

### CODE REVIEW

**Comment by shaffeeullah** [comment]
Do we need this since there are no library changes?

**Comment by ddelgrosso1** [comment]
I guess that depends on how we want to handle these types of changes going forward. I know in our meeting there was some discussion about the value of tests like this. Was a decision reached about whether or not we want to continue adding tests for things like this?

**Comment by shaffeeullah** [comment]
I don't think we want to handle changes like this. Let's make sure we're testing our library and not just testing GCS. I think this just adds bloat.

**Comment by ddelgrosso1** [comment]
As this did not require a code change the tests are not warranted. Closing.

**Pull request closed without merging**
