### PR TITLE
Added examples how to upload files

### PR DESCRIPTION
**Pull request by armgit5**
Added examples as middleware functions to upload a single file or multiple files.
Added missing json key file in Stroge constructor.
Cleaned up links by changing long links to embedded links in sentences.

Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by armgit5** [comment]
I signed it!

**Comment by kinwa91** [comment]
Hi @armgit5, thank you for sharing your experience with setting up Cloud Storage with Express, that's really helpful to a lot of folks out there since it's such a popular framework.

We don't usually host specific use cases on the `README.md` file of the library - @fhinkel, where do we put solutions by contributors?

**Comment by armgit5** [comment]
Thank you for your reply, @kinwa91. Please let me know if there is any place I could contribute and share some examples I've been using for my project. I really think it'd be very helpful to others :-) really like your google cloud solutions :-)

**Comment by JustinBeckwith** [comment]
Apologies for the delay on this one.  And thank you so much!  The best way to add a sample is to create a new `*.js` file in the samples directory, similar to the others already in there.  That way, we can add tests to make sure the samples don't break over time.  If you'd be willing to do this - we'd really appreciate it!

**Comment by fhinkel** [comment]
Hi, thanks for the PR! [This](https://github.com/GoogleCloudPlatform/community) would be the right place, would you be willing to wrap it in a tutorial?

**Comment by armgit5** [comment]
Happy New Year 2019 to you all, I wouldn't mind that at all, would really be happy to do it :-)

**Comment by JustinBeckwith** [comment]
Thanks again @armgit5!  If you need any help submitting the community tutorial - please do let us know!

**Comment by armgit5** [comment]
I'm sorry it takes me a long time, I still want to put those tutorial still. I will definitely come back to you again.

**Pull request closed without merging**
