### PR TITLE
feat(userAgent): allow for optional user agent to be provided

### PR DESCRIPTION
**Pull request by averikitsch**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by averikitsch** [comment]
@JustinBeckwith

**Review by JustinBeckwith — APPROVED** [review]
I can't say with 100% confidence what we want to have happen on the backend will happen, because storage has some weirdness with OnePlatform and usage tracking.  @frankyn is there a way to test this?  That having been said, this don't hurt.

**Comment by frankyn** [comment]
I'll follow-up with both of you over email due to internal only information.

**Comment by averikitsch** [comment]
Looks like the system tests may be flaky.

**Comment by frankyn** [comment]
Project overground may be causing this... will raise in today's sync and report back.

cc: @amanda-tarafa 
```
  1) storage
       HMAC keys
         should create an HMAC key for a service account:
     Error: Request violates constraint 'constraints/iam.disableServiceAccountKeyCreation'
      at new ApiError (node_modules/@google-cloud/common/build/src/util.js:59:15)
      at Util.parseHttpRespBody (node_modules/@google-cloud/common/build/src/util.js:194:38)
      at Util.handleResp (node_modules/@google-cloud/common/build/src/util.js:135:117)
      at /workspace/node_modules/@google-cloud/common/build/src/util.js:434:22
      at onResponse (node_modules/retry-request/index.js:214:7)
      at /workspace/node_modules/teeny-request/build/src/index.js:219:13
          -> /workspace/node_modules/teeny-request/src/index.ts:325:11
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5
```

**Comment by amanda-tarafa** [comment]
Yes, definetely seems to be related to overground. Create an internal bug, and assign it to me, with the following info:
- Project ID this is happening.
- What exactly is this method trying to do? Is it really trying to create and download a Service Account Key?

**Pull request merged**
