### PR TITLE
refactor(ts): merge initial TypeScript conversion

### PR DESCRIPTION
**Pull request by kinwa91**
BREAKING CHANGE:

Storage will need to be imported as a named import:
```js
const { Storage } = require('@google-cloud/storage');
```

Storage cannot be instantiated without new:
```js
𝘅 const storage = Storage();  // deprecated
✔ const storage = new Storage();
```

### CODE REVIEW

**Comment by kinwa91** [comment]
[Do not merge yet] - some system test failures after merging from master.

**Comment by JustinBeckwith** [comment]
👋 How's this going?

**Comment by kinwa91** [comment]
I am still tracking down those places within our docs that uses the old initialization style.

**Comment by kinwa91** [comment]
@JustinBeckwith i think you might have to force merge this since lint is still failing.

**Comment by sabrehagen** [comment]
When will this be released?

**Pull request merged**
