### PR TITLE
chore: update createBucketRequest in createNewBucket.js

### PR DESCRIPTION
**Pull request by kembala**
Example is outdated as the parameter type is:
}
```
export interface CreateBucketRequest {
    archive?: boolean;
    coldline?: boolean;
    cors?: Cors[];
    dra?: boolean;
    multiRegional?: boolean;
    nearline?: boolean;
    regional?: boolean;
    requesterPays?: boolean;
    retentionPolicy?: object;
    standard?: boolean;
    userProject?: string;
    location?: string;
    versioning?: Versioning;
}
```

### CODE REVIEW

**Review by sofisl — APPROVED** [review]

**Comment by sofisl** [comment]
Hi @kemenesbalazs, thanks for your contribution! Before we can merge, can you sign the CLA? (see comment above). Thanks!

**Comment by stephenplusplus** [comment]
I think this is a TypeScript issue. We should definitely be supporting `storageClass`, it just looks like the annotation doesn't show that.

**Comment by kemenesbalazs** [comment]
@googlebot I signed it!

**Comment by stephenplusplus** [comment]
@kemenesbalazs Thank you for pointing this out. The real issue was that the TypeScript interface was not allowing `storageClass` to be user-defined. I've added that to the interface in a new PR: #1299.

**Pull request closed without merging**
