### PR TITLE
docs: Document `DownscopedClient` Usage

### LINKED ISSUE #1522: Document how to use a CredentialAccessBoundary/DownscopedToken
There is currently no documentation or example anywhere obvious that describes how you are supposed to use a `CredentialAccessBoundary` or `DownscopedClient `with `Storage` either in this library or in `google-auth-library`. It would be very helpful to have this information for issuing onetime tokens for accessing specific resources within a bucket. 

This seems like a relatively common need for projects that deal with file uploads/downloads and so would be worth explicitly documenting since it's not remotely close to obvious.

### PR DESCRIPTION
**Pull request by danielbankhead**
Await https://github.com/googleapis/nodejs-common/pull/733

Fixes #1522 🦕

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
No objection to this PR but this looks like something we should probably further document in a sample at some point in the near future.

**Review by ddelgrosso1 — APPROVED** [review]

**Comment by ddelgrosso1** [comment]
Added 'do not merge' until common is released.

**Comment by danielbankhead** [comment]
> No objection to this PR but this looks like something we should probably further document in a sample at some point in the near future.

I think it's fair to add the sample to this PR; makes the resolution a bit more comprehensive.

**Comment by danielbankhead** [comment]
Offline update: We'll need to sync with the rest of the team on rolling out DownscopedClient for Storage samples to the other langs. Will merge this now, pending a sample directly in this repo in the future. In the meantime, these will suffice for Node.js for now:
- https://github.com/googleapis/google-auth-library-nodejs#sample-usage-1
- https://github.com/googleapis/google-auth-library-nodejs/blob/main/samples/downscopedclient.js

**Pull request merged**
