### PR TITLE
feat(file): allow setting configPath of resumable upload

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes https://github.com/googleapis/gcs-resumable-upload/issues/132

## Blocked

- [x] https://github.com/googleapis/gcs-resumable-upload/pull/200

### CODE REVIEW

**Comment by stephenplusplus** [comment]
We actually don't want to merge this yet, as I think we are rolling back gcs-resumable-upload to pre 1.0.

**Comment by JustinBeckwith** [comment]
@jkwlui @stephenplusplus this is getting a tad moldy.  Do we have clear steps to get it merged?

**Comment by JustinBeckwith** [comment]
@stephenplusplus @jkwlui I'm going to close this out for now.

**Comment by stephenplusplus** [comment]
@jkwlui @JustinBeckwith this one should be ready to go now. Please take a look!

**Pull request merged**
