### PR TITLE
fix: remove compodoc dev dependency

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
This dependency was/is breaking CI builds for Node 15 due to only supporting 12, 14, 16.

**Comment by shaffeeullah** [comment]
Is it not necessary?

**Comment by ddelgrosso1** [comment]
@shaffeeullah that is what I was trying to see by removing it and running everything through CI. It was brought in as part of the GCS Resumable move but not sure what it was doing there or if we need it here.

**Review by shaffeeullah — APPROVED** [review]

**Comment by ddelgrosso1** [comment]
This was used in the gcs-resumable-upload library to generate the documentation. It is not needed here as we are not publicly exposing those interfaces through storage but rather just consuming the code that was internalized here. I feel comfortable that this can be safely removed.

**Pull request merged**
