### PR TITLE
Repository Migration

### PR DESCRIPTION
**Pull request by lukesneeringer**
This is the complete repository migration for `@google-cloud/storage`.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Some Windows issues:

```
$ npm run system-test
> @google-cloud/storage@1.2.1 system-test C:\Users\sawch\dev\nodejs-storage
> repo-tools test run --cmd node_modules/.bin/mocha -- system-test/*.js --no-timeouts

run: Executing tests in: C:\Users\sawch\dev\nodejs-storage
run: Running: node_modules/.bin/mocha system-test/*.js --no-timeouts
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by lukesneeringer** [comment]
@jmdobry That looks like a path separator issue?

**Comment by jmdobry** [comment]
Spent some time testing on windows. If we change it from `node_modules/.bin/mocha` to just `mocha`, then it works. Note that `npm run-script` puts everything in `node_modules/.bin` into the PATH during execution.

**Comment by lukesneeringer** [comment]
Okay, here we go. (The coverage failure is "no baseline", which obviously I can not do anything about.)

**Pull request merged**
